#!/usr/bin/env bash

#----- Fancy Messages -----#
function show_error {
  echo -e "\033[1;31m$@\033[m" 1>&2
}

function show_success {
  echo -e "\033[1;32m$@\033[0m"
}

function show_warning {
  echo -e "\033[1;33m$@\033[0m"
}

function show_info {
  echo -e "\033[1;34m$@\033[0m"
}
