#!/usr/bin/env bash

CONF='/etc/cntlm.conf'

function task_cntlm_install {
    
    echo "Please open proxy settings via gui and click on apply everywhere"
    echo "After succefully doing that, press any key."
    gsettings set org.gnome.system.proxy mode 'manual'
    gsettings set org.gnome.system.proxy use-same-proxy false
    gsettings set org.gnome.system.proxy.http host '127.0.0.1'
    gsettings set org.gnome.system.proxy.http port 3128
    gsettings set org.gnome.system.proxy.https host '127.0.0.1'
    gsettings set org.gnome.system.proxy.https port 3128
    gsettings set org.gnome.system.proxy.ftp host '127.0.0.1'
    gsettings set org.gnome.system.proxy.ftp port 3128
    read foo
    source "$HOME/.bashrc"
    echo "Installing CNTLM Proxy authentication"
    sudo dpkg -i data/cntlm_0.92.3-1ubuntu1_amd64.deb
}

function task_cntlm_config {
  echo "Configure CNTLM Proxy authentication";

  echo -n "User: ";
  read USER_NAME;
  sudo sed -i "/^Username/c\Username  $USER_NAME" "$CONF"

  echo -n "Domain: ";
  read DOMAIN;
  sudo sed -i "/^Domain/c\Domain\  $DOMAIN" "$CONF"

  sudo sed -i "/^Password/c\# Password" "$CONF"

  echo -n "Listen(host:port): "
  read LISTEN

  sudo sed -i "/^Proxy/c\Proxy  ${LISTEN}" "$CONF"

  echo -n "Password: ";
  PW="$(cntlm -u $USER_NAME -d $DOMAIN -f -H)";

  echo " ";

  echo "Adding to /etc/cntlm.conf";
  PASSLM="$(echo "$PW" | grep PassLM)";
  PASSNT="$(echo "$PW" | grep -e 'PassNT ')";
  PASSNTLM="$(echo "$PW" | grep PassNTLMv2)";

  sudo sed -i '/PassLM /c\'"$PASSLM" "$CONF"
  sudo sed -i '/PassNT /c\'"$PASSNT" "$CONF"
  sudo sed -i '/PassNTLMv2 /c\'"$PASSNTLM" "$CONF"

  sudo sed -i "/^### Only for user/d" "$CONF";

  echo -n "NoProxy(comma seperated list): "
  read NO_PROXY
  sudo sed -i "/^NoProxy/c\NoProxy  $(echo $NO_PROXY | sed s/','/'\,'/ )" "$CONF"

  # add environment variables
  if ! grep "export http_proxy" "$HOME/.bashrc"; then
		echo '
		# Proxy
		export http_proxy="http://127.0.0.1:3128"
		export https_proxy="http://127.0.0.1:3128"
		export ftp_proxy="http://127.0.0.1:3128"
		export HTTP_PROXY="http://127.0.0.1:3128"
		export HTTPS_PROXY="http://127.0.0.1:3128"
		export FTP_PROXY="http://127.0.0.1:3128"
		' >> "$HOME/.bashrc";
		source "$HOME/.bashrc";
  fi

  ## make apt work
  echo 'Acquire::http::Pipeline-Depth 0;' | sudo tee -a "/etc/apt/apt.conf";
  echo 'Acquire::http::No-Cache=True;' | sudo tee -a "/etc/apt/apt.conf";

  echo "Restarting service"
  sudo service cntlm restart
}

function task_cntlm_new_pw {
  shopt -s extglob

  USER_NAME="$(sudo cat "$CONF" | grep Username)";
  USER_NAME="${USER_NAME##Username+([[:space:]])}";

  DOMAIN="$(sudo cat "$CONF" | grep Domain)";
  DOMAIN="${DOMAIN##Domain+([[:space:]])}";

  echo "User: $USER_NAME"
  echo "Domain: $DOMAIN"

  echo -n "Password: ";
  PW="$(cntlm -u $USER_NAME -d $DOMAIN -f -H)";


  echo "Adding to /etc/cntlm.conf";
  PASSLM="$(echo "$PW" | grep PassLM)";
  PASSNT="$(echo "$PW" | grep -e 'PassNT ')";
  PASSNTLM="$(echo "$PW" | grep PassNTLMv2)";

  sudo sed -i '/PassLM /c\'"$PASSLM" "$CONF"
  sudo sed -i '/PassNT /c\'"$PASSNT" "$CONF"
  sudo sed -i '/PassNTLMv2 /c\'"$PASSNTLM" "$CONF"

  echo "Restarting service"
  sudo service cntlm restart

  shopt -u extglob
}
