#!/bin/bash

# tweak config folder path here
CONF='/etc/cntlm.conf'
CNTLM_ADDRESS="http://localhost:3128"
APT_CONF='/etc/apt/apt.conf'

function cntlm-install {
    echo "Installing CNTLM Proxy authentication"
    sudo dpkg -i data/cntlm_0.92.3_amd64.deb
}

function cntlm-config {
  echo "Configure CNTLM Proxy authentication";

  echo -n "User: ";
  read USER_NAME;
  sudo sed -i "/^Username/c\Username  $USER_NAME" "$CONF"

  echo -n "Domain: ";
  read DOMAIN;
  sudo sed -i "/^Domain/c\Domain\  $DOMAIN" "$CONF"

  sudo sed -i "/^Password/c\# Password" "$CONF"

  echo -n "Listen(host:port): "
  read LISTEN

  sudo sed -i "/^Proxy/c\Proxy  ${LISTEN}" "$CONF"

  echo -n "Password: ";
  PW="$(cntlm -u $USER_NAME -d $DOMAIN -f -H)";

  echo " ";

  echo "Adding to /etc/cntlm.conf";
  PASSLM="$(echo "$PW" | grep PassLM)";
  PASSNT="$(echo "$PW" | grep -e 'PassNT ')";
  PASSNTLM="$(echo "$PW" | grep PassNTLMv2)";

  sudo sed -i '/PassLM /c\'"$PASSLM" "$CONF"
  sudo sed -i '/PassNT /c\'"$PASSNT" "$CONF"
  sudo sed -i '/PassNTLMv2 /c\'"$PASSNTLM" "$CONF"

  sudo sed -i "/^### Only for user/d" "$CONF";

  echo -n "NoProxy(comma seperated list): "
  read NO_PROXY
  sudo sed -i "/^NoProxy/c\NoProxy  $(echo $NO_PROXY | sed s/','/'\,'/ )" "$CONF"

  # adjust gui proxy settings
  gsettings set org.gnome.system.proxy use-same-proxy false
  gsettings set org.gnome.system.proxy.ftp host '127.0.0.1'
  gsettings set org.gnome.system.proxy.ftp port 3128
  gsettings set org.gnome.system.proxy.http host '127.0.0.1'
  gsettings set org.gnome.system.proxy.http port 3128
  gsettings set org.gnome.system.proxy.https host '127.0.0.1'
  gsettings set org.gnome.system.proxy.https port 3128

  # add environment variables
  echo 'CNTLM_ADDRESS=http://localhost:3128' >> "$HOME/.bashrc";
  echo 'http_proxy="$CNTLM_ADDRESS"' >> "$HOME/.bashrc";
  echo 'https_proxy="$CNTLM_ADDRESS"' >> "$HOME/.bashrc";
  source "$HOME/.bashrc";

  # make apt work

  echo 'Acquire::http::proxy "http://localhost:3128/";' | sudo tee -a "$APT_CONF";
  echo 'Acquire::https::proxy "https://localhost:3128/";' | sudo tee -a "$APT_CONF";

  echo "Restarting service"
  sudo service cntlm restart
}

function cntlm-new-pw {
  shopt -s extglob

  USER_NAME="$(sudo cat "$CONF" | grep Username)";
  USER_NAME="${USER_NAME##Username+([[:space:]])}";

  DOMAIN="$(sudo cat "$CONF" | grep Domain)";
  DOMAIN="${DOMAIN##Domain+([[:space:]])}";

  echo "User: $USER_NAME"
  echo "Domain: $DOMAIN"

  echo -n "Password: ";
  PW="$(cntlm -u $USER_NAME -d $DOMAIN -f -H)";


  echo "Adding to /etc/cntlm.conf";
  PASSLM="$(echo "$PW" | grep PassLM)";
  PASSNT="$(echo "$PW" | grep -e 'PassNT ')";
  PASSNTLM="$(echo "$PW" | grep PassNTLMv2)";

  sudo sed -i '/PassLM /c\'"$PASSLM" "$CONF"
  sudo sed -i '/PassNT /c\'"$PASSNT" "$CONF"
  sudo sed -i '/PassNTLMv2 /c\'"$PASSNTLM" "$CONF"

  echo "Restarting service"
  sudo service cntlm restart

  shopt -u extglob
}
