#!/bin/bash

# stop executing script on error
set -e

red='\033[1;31m';
green='\033[1;32m';
yellow='\033[1;33m';
blue='\033[1;34m';
purple='\033[1;35m';
cyan='\033[1;36m';
reset='\E(B\E[m';

function task_mirrors {
  echo -e "${cyan}Switching to german update server${reset}"
  sudo sed -i 's/us\.archive\.ubuntu\.com/de.archive.ubuntu.com/' /etc/apt/sources.list
}

function task_install {
  echo -e "${cyan}Installing packages and apps${reset}"
  # add third party ppas
  # atom editor
  sudo add-apt-repository -y ppa:webupd8team/atom
  # diodon clipboard manager
  sudo add-apt-repository -y ppa:diodon-team/stable
  # numix
  sudo add-apt-repository -y ppa:numix/ppa
  # nautlius embedded terminal
  # sudo add-apt-repository -y ppa:flozz/flozz

  # indicator keylock
  sudo add-apt-repository -y ppa:tsbarnes/indicator-keylock

  # update
  sudo apt-get update

  # upgrade
  sudo apt-get -y upgrade
  sudo apt-get -y dist-upgrade

  # install packages
  sudo apt-get -y install atom
  sudo apt-get -y install htop
  sudo apt-get -y install git
  sudo apt-get -y install unity-tweak-tool
  sudo apt-get -y install guake
  sudo apt-get -y install dconf-editor
  sudo apt-get -y install compizconfig-settings-manager
  sudo apt-get -y install gksu
  sudo apt-get -y install vim
  sudo apt-get -y install gparted
  sudo apt-get -y install openjdk-8-jdk
  sudo apt-get -y install chromium-browser
  # sudo apt-get -y install nautilus-terminal
  sudo apt-get -y install gcolor2
  sudo apt-get -y install inkscape
  sudo apt-get -y install diodon
  sudo apt-get -y install meld
  sudo apt-get -y install nautilus-compare
  sudo apt-get -y install thunderbird
  sudo apt-get -y install numix-gtk-theme
  sudo apt-get -y install numix-icon-theme-circle
  sudo apt-get -y install pandoc
  sudo apt-get -y install indicator-keylock
  sudo apt-get -y install nautilus-dropbox
  sudo apt-get -y install python-pip
  sudo apt-get -y install libwww-dict-leo-org-perl

  # clean up installed packages
  sudo apt-get -y autoremove
}

# download and install webstorm
function task_webstorm {
  echo -e "${cyan}Installing webstorm${reset}"
  if [ ! -d "/opt/webstorm" ]; then

    wget -O data/webstorm.tar.gz "https://download.jetbrains.com/webstorm/WebStorm-2016.1.2b.tar.gz"
    tar -xzvf data/webstorm.tar.gz --directory data/
    mv data/WebStorm-* data/webstorm
    sudo cp -r data/webstorm /opt/webstorm
    rm -rf data/webstorm*
    /opt/webstorm/bin/webstorm.sh &
  fi
}

function task_git {
  git config --global user.name "Umut Topuzoğlu"
  git config --global user.email "uloco@schiefewelt.de"
  git config --global push.default simple
  git config --global credential.helper cache
  git config --global svn.rmdir true
}

# set up diodon key binding
function task_diodon {
  echo -e "${cyan}Setting up diodon shortcut CTRL+SUPER+V${reset}"
  gsettings set org.gnome.settings-daemon.plugins.media-keys custom-keybindings "['/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/']"
  gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/ name 'Diodon Clipboard Manager'
  gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/ command '/usr/bin/diodon'
  gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/ binding '<Primary><Super>v'
}


# add startup applications: diodon guake
function task_autostart {
  echo -e "${cyan}Adding apps to autostart${reset}"
  if [ ! -d "$HOME/.config/autostart/" ]; then
    mkdir "$HOME/.config/autostart/"
  fi
  cp data/autostart/* "$HOME/.config/autostart/"
}

# middle mouse click with three fingers
function task_middleClick {
  if synclient &>/dev/null && ! grep 'synclient TapButton3=2' "$HOME/.bashrc" &>/dev/null; then
    echo -e "${cyan}Touchpad detected, adding middle click on 3 finger tap.${reset}"
    echo "synclient TapButton3=2" >> $HOME/.bashrc
    source "$HOME/.bashrc"
  fi
}

function task_npm {
  # get nvm and set up npm
  curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.31.0/install.sh | bash
  source $HOME/.bashrc
  nvm install stable
  nvm alias default stable
  nvm use stable

  npm install -g \
    babel-cli \
    bower \
    cordova \
    esformatter \
    eslint \
    eslint-config-angular \
    eslint-config-google \
    eslint-plugin-angular \
    flow-bin \
    grunt-cli \
    gulp \
    http-server \
    ionic \
    jsdoc \
    karma-cli \
    live-server
}

# install font source code pro

function task_fonts {
echo -e "${cyan}Installing missing fonts.${reset}"
  if [ ! -d "$HOME/.fonts" ]; then
    mkdir ~/.fonts
  fi
  tar -xzvf data/source-code-pro.tar.gz
  cp -f source-code-pro/* ~/.fonts
  fc-cache -f -v
  rm -r source-code-pro/
}


# grob customization
function task_grob {
  echo "grobCustomization"

  source ./cntlm

  task_cntlm_install;
  task_cntlm_config;

  # set npm registry
  #npm config set registry http://gmvm003lx:8081/nexus/content/repositories/npmjs/

}

function task_folders {
  mkdir -pv "$HOME/Source/github"
  mkdir -pv "$HOME/Source/bitbucket"
  mkdir -pv "$HOME/Software"
  mkdir -pv "$HOME/Scripts"
  mkdir -pv "$HOME/Screenshots"
  mkdir -pv "$HOME/tmp"
  mkdir -pv "$HOME/Workshops"
  mkdir -pv "$HOME/Virtual Machines"
}

function task_dreymar {
  echo -e "${cyan}Set up dreymars extended keyboard layer ${reset}"

  if ls /usr/share/X11/dbak-* 1> /dev/null 2>&1; then
    echo -e "${purple}  Already installed, skipping.${reset}"
  else
    git clone https://github.com/DreymaR/BigBagKbdTricks_XKB.git
    cd BigBagKbdTricks_XKB
    chmod u+x install-dreymar-xmod.sh
    ./install-dreymar-xmod.sh -o
    gsettings set org.gnome.desktop.input-sources xkb-options "['lv5:caps_switch_lock', 'misc:extend', 'shift:both_capslock', 'compose:rctrl']"
    cd ..
    rm -rf BigBagKbdTricks_XKB
  fi
}

function task_language {
  sudo apt-get -y install $(check-language-support -l de)
}

function task_gsettings {
  gsettings set org.gnome.desktop.input-sources sources "[('xkb','de')]"
  gsettings set com.canonical.indicator.datetime show-date true
  gsettings set com.canonical.indicator.datetime show-day true
  gsettings set com.canonical.indicator.datetime show-week-numbers true
  gsettings set com.canonical.indicator.datetime time-format '24-hour'
  gsettings set com.canonical.indicator.datetime timezone-name 'Europe/Berlin Mindelheim'
  gsettings set com.canonical.indicator.messages applications "['thunderbird.desktop']"
  gsettings set com.canonical.Unity integrated-menus true
  gsettings set org.compiz.integrated show-hud "['disabled']"
  gsettings set org.freedesktop.ibus.general engines-order "['xkb:de:nodeadkeys:ger']"
  gsettings set org.freedesktop.ibus.general preload-engines "['xkb:de:nodeadkeys:ger']"
  gsettings set org.gnome.calculator button-mode 'advanced'
  gsettings set org.gnome.desktop.interface gtk-theme 'Numix'
  gsettings set org.gnome.desktop.interface icon-theme 'Numix-Circle'
  gsettings set org.gnome.desktop.interface monospace-font-name 'Source Code Pro Medium 11'
  #gsettings set org.gnome.desktop.lockdown disable-lock-screen true
  gsettings set org.gnome.desktop.notifications application-children "['diodon', 'thunderbird']"
  #gsettings set org.gnome.desktop.screensaver lock-enabled false
  gsettings set org.gnome.desktop.screensaver ubuntu-lock-on-suspend false
  gsettings set org.gnome.desktop.wm.keybindings maximize "['<Primary><Super>Up']"
  gsettings set org.gnome.desktop.wm.keybindings move-to-workspace-down "['<Control><Alt><Super>Down']"
  gsettings set org.gnome.desktop.wm.keybindings move-to-workspace-left "['<Control><Alt><Super>Left']"
  gsettings set org.gnome.desktop.wm.keybindings move-to-workspace-right "['<Control><Alt><Super>Right']"
  gsettings set org.gnome.desktop.wm.keybindings move-to-workspace-up "['<Control><Alt><Super>Up']"
  gsettings set org.gnome.desktop.wm.keybindings show-desktop "['<Super>d']"
  gsettings set org.gnome.desktop.wm.keybindings switch-to-workspace-down "['<Alt><Super>Down']"
  gsettings set org.gnome.desktop.wm.keybindings switch-to-workspace-left "['<Alt><Super>Left']"
  gsettings set org.gnome.desktop.wm.keybindings switch-to-workspace-right "['<Alt><Super>Right']"
  gsettings set org.gnome.desktop.wm.keybindings switch-to-workspace-up "['<Alt><Super>Up']"
  gsettings set org.gnome.desktop.wm.preferences mouse-button-modifier '<Super>'
  gsettings set org.gnome.desktop.wm.preferences theme 'Numix'
  gsettings set org.gnome.gnome-screenshot auto-save-directory "'file://$HOME/Pictures/Screenshots'"
  gsettings set org.gnome.nautilus.preferences default-folder-viewer 'list-view'
  gsettings set org.gnome.nautilus.preferences default-folder-viewer 'list-view'
  gsettings set org.gnome.nautilus.preferences executable-text-activation 'ask'
  gsettings set org.gnome.nautilus.preferences executable-text-activation 'ask'
  gsettings set org.gnome.seahorse.manager keyrings-selected "['secret-service://login', 'gnupg://']"
  gsettings set org.gnome.settings-daemon.plugins.media-keys calculator '<Super>asciicircum'
  gsettings set com.canonical.Unity.Launcher favorites "['unity://expo-icon', 'unity://devices', 'application://firefox.desktop', 'application://chromium-browser.desktop', 'application://org.gnome.Nautilus.desktop', 'application://gnome-terminal.desktop', 'application://atom.desktop', 'application://jetbrains-webstorm.desktop', 'application://inkscape.desktop', 'application://gcolor2.desktop', 'application://gnome-system-monitor.desktop', 'unity://running-apps']"
  gsettings set org.gnome.settings-daemon.plugins.media-keys terminal '<Super>r'
}

function task_dconf {
  dconf write /org/compiz/profiles/unity/plugins/core/vsize 2
  dconf write /org/compiz/profiles/unity/plugins/core/hsize 2
  dconf write /org/compiz/profiles/unity/plugins/unityshell/launcher-minimize-window true
  dconf write /org/gnome/desktop/wm/preferences/action-middle-click-titlebar "'none'"
  dconf write /org/gtk/settings/file-chooser/show-hidden true
  dconf write /org/gnome/nautilus/list-view/use-tree-view true
  dconf write /com/canonical/indicator/power/show-time true
  dconf write /com/canonical/indicator/power/show-percentage true
}

function task_cursor {
  git clone https://github.com/uloco/numix-cursor.git
  if [[ ! -d "$HOME/.icons" ]]; then
    mkdir "$HOME/.icons"
  fi
  if [[ ! -d "$HOME/.icons/Numix-Cursor" ]]; then
    cp -rv numix-cursor/theme/Numix-Cursor "$HOME/.icons/Numix-Cursor"
  fi
  gsettings set org.gnome.desktop.interface cursor-theme "Numix-Cursor"
  rm -rf numix-cursor/

}

function task_hardcodefixer {
  git clone https://github.com/Foggalong/hardcode-fixer.git
  cd hardcode-fixer
  sudo ./fix.sh
  cd ..
  rm -rf hardcode-fixer

  # fix webstorm
  sudo sed -i "/^Icon/c\Icon=webstorm" /usr/share/applications/jetbrains-webstorm.desktop
}

# import terminal color profile
# get atom settings
# customize bash prompt with git status bar (bash it?)
# set up aliases

# install android sdk
function task_android {

  # perhaps this is enough
  sudo apt-get install -y android-sdk

  # download android sdk
  # $CURRENT_DIR=$(pwd);

  # wget https://dl.google.com/android/android-sdk_r24.4.1-linux.tgz

  # tar -xvf android-sdk_r24.4.1-linux.tgz
  # cd android-sdk-linux/tools

  # # install all sdk packages
  # ./android update sdk --no-ui

  # # set path
  # $HOME/.bashrc >> export PATH=${PATH}:$HOME/sdk/android-sdk-linux/platform-tools:$HOME/sdk/android-sdk-linux/tools:$HOME/sdk/android-sdk-linux/build-tools/22.0.1/
  # source "$HOME/.bashrc"

  # # adb
  # sudo apt-get install libc6:i386 libstdc++6:i386
  # # aapt
  # sudo apt-get install zlib1g:i386

  # cd "$CURRENT_DIR";
}

function task_terminal {
  dconf set /org/gnome/terminal/legacy/profiles:/list "['c54d3223-6d98-4650-98a9-37d912292c4b']"
  dconf set /org/gnome/terminal/legacy/profiles:/default 'c54d3223-6d98-4650-98a9-37d912292c4b'

  dconf set /org/gnome/terminal/legacy/profiles:/:c54d3223-6d98-4650-98a9-37d912292c4b/palette "['rgb(80,80,80)', 'rgb(255,46,63)', 'rgb(111,214,93)', 'rgb(255,111,35)', 'rgb(52,118,255)', 'rgb(152,97,248)', 'rgb(0,205,179)', 'rgb(255,252,194)', 'rgb(124,124,124)', 'rgb(255,100,128)', 'rgb(63,197,107)', 'rgb(249,200,89)', 'rgb(0,177,254)', 'rgb(182,141,255)', 'rgb(179,139,125)', 'rgb(255,254,227)']"

  dconf set /org/gnome/terminal/legacy/profiles:/:c54d3223-6d98-4650-98a9-37d912292c4b/scrollback-lines '999999'
}

function task_runall {
  # task_grob
  task_mirrors
  task_install
  task_language
  task_fonts
  task_folders
  task_autostart
  task_webstorm
  task_git
  task_diodon
  # task_middleClick
  # task_npm
  task_gsettings
  task_dreymar
  task_dconf
  task_terminal
  task_cursor
  task_hardcodefixer
  task_android
}

if [ ! $# -eq 0 ]
  then
    "$1"
  else
    task_runall
fi

echo -e \
  "${cyan}" \
  "\n ****************************************************************************** \n" \
  "****************************************************************************** \n" \
  "UBUNTU POST INITIALIZATION SUCCESSFULL! \n" \
  "Things you will have to do manually: \n" \
  "============================================================================== \n" \
  "- Install Thunderbird addons: Minimize to Tray, Lightning, add email accounts \n" \
  "- Import compiz config settings from file 'data/ccsm.profile'\n" \
  "- Configure guake preferences\n" \
  "- \n" \
  "- \n"   \
  "${reset}";
