#!/usr/bin/env bash

function task_mirrors {
  echo -e "${echo_cyan}Switching to german update server${echo_normal}"
  sudo sed -i 's/us\.archive\.ubuntu\.com/de.archive.ubuntu.com/' /etc/apt/sources.list
}

function task_install {
  echo -e "${echo_cyan}Installing packages and apps${echo_normal}"
  # add third party ppas

  # atom editor
  sudo add-apt-repository -y ppa:webupd8team/atom

  # diodon clipboard manager
  sudo add-apt-repository -y ppa:diodon-team/stable

  # indicator keylock
  sudo add-apt-repository -y ppa:tsbarnes/indicator-keylock

  # take a break
  sudo add-apt-repository -y ppa:vlijm/takeabreak

  # java 7 needed for android 6.0
  sudo add-apt-repository -y ppa:openjdk-r/ppa

  # update
  sudo apt-get update

  # upgrade
  sudo apt-get -y upgrade
  sudo apt-get -y dist-upgrade

  # install packages
  sudo apt-get -y install atom \
    htop \
    git \
    unity-tweak-tool \
    guake \
    dconf-editor \
    compizconfig-settings-manager \
    gksu \
    vim \
    gparted \
    openjdk-8-jdk \
    openjdk-7-jdk \
    chromium-browser \
    # nautilus-terminal \
    gcolor2 \
    inkscape \
    diodon \
    meld \
    nautilus-compare \
    thunderbird \
    pandoc \
    indicator-keylock \
    nautilus-dropbox \
    python-pip \
    libwww-dict-leo-org-perl \
    gnome-tweak-tool \
    ppa-purge \
    buildnotify \
    checkinstall \
    takeabreak \
    synaptic

  # clean up installed packages
  sudo apt-get -y autoremove
}

# download and install webstorm
function task_webstorm {
  echo -e "${echo_cyan}Installing webstorm${echo_normal}"
  if [ ! -d "/opt/webstorm" ]; then

    wget -O data/webstorm.tar.gz "https://download.jetbrains.com/webstorm/WebStorm-2016.1.3.tar.gz"
    tar -xzvf data/webstorm.tar.gz --directory data/
    mv data/WebStorm-* data/webstorm
    sudo cp -r data/webstorm /opt/webstorm
    rm -rf data/webstorm*
    sudo chown -R $USER:$USER /opt/webstorm
    /opt/webstorm/bin/webstorm.sh &
  fi
}

function task_git {
  echo -e "${echo_cyan}Initial git config${echo_normal}"
  echo -n "Git Name: "
  read GIT_USER
  echo -n "Git Email"
  read GIT_EMAIL
  git config --global user.name "$GIT_USER"
  git config --global user.email "$GIT_EMAIL"
  git config --global push.default simple
  git config --global credential.helper cache
  git config --global svn.rmdir true
}

# set up diodon key binding
function task_diodon {
  echo -e "${echo_cyan}Setting up diodon shortcut CTRL+SUPER+V${echo_normal}"
  gsettings set org.gnome.settings-daemon.plugins.media-keys custom-keybindings "['/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/']"
  gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/ name 'Diodon Clipboard Manager'
  gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/ command '/usr/bin/diodon'
  gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/ binding '<Primary><Super>v'
}


# add startup applications: diodon guake
function task_autostart {
  echo -e "${echo_cyan}Adding apps to autostart${echo_normal}"
  if [ ! -d "$HOME/.config/autostart/" ]; then
    mkdir "$HOME/.config/autostart/"
  fi
  cp data/autostart/* "$HOME/.config/autostart/"
}

# middle mouse click with three fingers
function task_middleClick {
  if synclient &>/dev/null && ! grep 'synclient TapButton3=2' "$HOME/.bashrc" &>/dev/null; then
    echo -e "${echo_cyan}Touchpad detected, adding middle click on 3 finger tap.${echo_normal}"
    echo "synclient TapButton3=2" >> $HOME/.bashrc
    source "$HOME/.bashrc"
  fi
}

function task_npm {
  # get nvm and set up npm
  echo -e "${echo_cyan}Setting up nvm, nodeJS and npm${echo_normal}"
  curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.31.0/install.sh | bash
  source $HOME/.bashrc
  nvm install stable
  nvm alias default stable
  nvm use stable

  npm install -g \
    npm \
    babel-cli \
    bower \
    cordova \
    esformatter \
    eslint \
    eslint-config-angular \
    eslint-config-google \
    eslint-plugin-angular \
    flow-bin \
    grunt-cli \
    gulp \
    http-server \
    ionic \
    jsdoc \
    karma-cli \
    live-server \
    ungit
}

# install font source code pro

function task_fonts {
echo -e "${echo_cyan}Installing missing fonts.${echo_normal}"
  if [ ! -d "$HOME/.fonts" ]; then
    mkdir ~/.fonts
  fi
  tar -xzvf data/source-code-pro.tar.gz
  cp -f source-code-pro/* ~/.fonts
  fc-cache -f -v
  rm -r source-code-pro/

  gsettings set org.gnome.desktop.interface monospace-font-name 'Source Code Pro Medium 11'
}

function task_folders {
  echo -e "${echo_cyan}Creating default folders${echo_normal}"
  mkdir -pv "$HOME/Source/github"
  mkdir -pv "$HOME/Source/bitbucket"
  mkdir -pv "$HOME/Software"
  mkdir -pv "$HOME/Scripts"
  mkdir -pv "$HOME/Screenshots"
  mkdir -pv "$HOME/tmp"
  mkdir -pv "$HOME/Workshops"
  mkdir -pv "$HOME/Virtual Machines"
}

function task_dreymar {
  echo -e "${echo_cyan}Set up dreymars extended keyboard layer ${echo_normal}"

  if ls /usr/share/X11/dbak-* 1> /dev/null 2>&1; then
    echo -e "${purple}  Already installed, skipping.${echo_normal}"
  else
    git clone https://github.com/DreymaR/BigBagKbdTricks_XKB.git
    cd BigBagKbdTricks_XKB
    chmod u+x install-dreymar-xmod.sh
    ./install-dreymar-xmod.sh -o
    gsettings set org.gnome.desktop.input-sources xkb-options "['lv5:caps_switch_lock', 'misc:extend', 'shift:both_capslock', 'compose:rctrl']"
    cd ..
    rm -rf BigBagKbdTricks_XKB
    # fix issues with f1-f12 media keys, capslock on numbers and space
    cp -f data/extend /usr/share/X11/xkb/symbols/extend

  fi
}

function task_language {
  echo -e "${echo_cyan}Installing missing language packs${echo_normal}"
  sudo apt-get -y install $(check-language-support -l en)
  sudo apt-get -y install $(check-language-support -l de)

  echo -e "${echo_cyan}Setting up locales${echo_normal}"
  sudo cp -f "data/locale" "/etc/default/locale"
}

function task_gsettings {
  echo -e "${echo_cyan}Setting gsettings values${echo_normal}"

  if [ ! -f "/usr/share/applications/jetbrains-webstorm.desktop" ]; then
    echo -e "${echo_red}Webstorm icon not found.${echo_normal}"
    echo -e "${echo_yellow}Please finish webstorm initiaization and then press any key to continue.${echo_normal}"
    read foo
  fi

  gsettings set org.gnome.desktop.input-sources sources "[('xkb','de+nodeadkeys')]"
  gsettings set com.canonical.indicator.datetime show-date true
  gsettings set com.canonical.indicator.datetime show-day true
  gsettings set com.canonical.indicator.datetime show-week-numbers true
  gsettings set com.canonical.indicator.datetime time-format '24-hour'
  gsettings set com.canonical.indicator.datetime timezone-name 'Europe/Berlin Mindelheim'
  gsettings set com.canonical.indicator.messages applications "['thunderbird.desktop']"
  gsettings set com.canonical.Unity integrated-menus true
  gsettings set org.compiz.integrated show-hud "['disabled']"
  gsettings set org.freedesktop.ibus.general engines-order "['xkb:de:nodeadkeys:ger']"
  gsettings set org.freedesktop.ibus.general preload-engines "['xkb:de:nodeadkeys:ger']"
  gsettings set org.gnome.calculator button-mode 'advanced'
  gsettings set org.gnome.desktop.session idle-delay 'uint32 0'
  #gsettings set org.gnome.desktop.lockdown disable-lock-screen true
  gsettings set org.gnome.desktop.notifications application-children "['diodon', 'thunderbird']"
  gsettings set org.gnome.desktop.screensaver lock-enabled false
  gsettings set org.gnome.desktop.screensaver ubuntu-lock-on-suspend true
  gsettings set org.gnome.desktop.wm.keybindings maximize "['<Primary><Super>Up']"
  gsettings set org.gnome.desktop.wm.keybindings move-to-workspace-down "['<Control><Alt><Super>Down']"
  gsettings set org.gnome.desktop.wm.keybindings move-to-workspace-left "['<Control><Alt><Super>Left']"
  gsettings set org.gnome.desktop.wm.keybindings move-to-workspace-right "['<Control><Alt><Super>Right']"
  gsettings set org.gnome.desktop.wm.keybindings move-to-workspace-up "['<Control><Alt><Super>Up']"
  gsettings set org.gnome.desktop.wm.keybindings show-desktop "['<Super>d']"
  gsettings set org.gnome.desktop.wm.keybindings switch-to-workspace-down "['<Alt><Super>Down']"
  gsettings set org.gnome.desktop.wm.keybindings switch-to-workspace-left "['<Alt><Super>Left']"
  gsettings set org.gnome.desktop.wm.keybindings switch-to-workspace-right "['<Alt><Super>Right']"
  gsettings set org.gnome.desktop.wm.keybindings switch-to-workspace-up "['<Alt><Super>Up']"
  gsettings set org.gnome.desktop.wm.keybindings toggle-shaded "['']"
  gsettings set org.gnome.desktop.wm.preferences mouse-button-modifier '<Super>'
  gsettings set org.gnome.gnome-screenshot auto-save-directory "'file://$HOME/Pictures/Screenshots'"
  gsettings set org.gnome.nautilus.preferences default-folder-viewer 'list-view'
  gsettings set org.gnome.nautilus.preferences executable-text-activation 'ask'
  gsettings set org.gnome.seahorse.manager keyrings-selected "['secret-service://login', 'gnupg://']"
  gsettings set org.gnome.settings-daemon.plugins.media-keys calculator '<Super>asciicircum'
  gsettings set com.canonical.Unity.Launcher favorites "['unity://expo-icon', 'unity://devices', 'application://firefox.desktop', 'application://chromium-browser.desktop', 'application://org.gnome.Nautilus.desktop', 'application://gnome-terminal.desktop', 'application://atom.desktop', 'application://jetbrains-webstorm.desktop', 'application://inkscape.desktop', 'application://gcolor2.desktop', 'application://gnome-system-monitor.desktop', 'unity://running-apps']"
  gsettings set org.gnome.settings-daemon.plugins.media-keys terminal '<Super>r'
}

function task_dconf {
  echo -e "${echo_cyan}Setting dconf settings${echo_normal}"
  dconf write /org/compiz/profiles/unity/plugins/core/vsize 2
  dconf write /org/compiz/profiles/unity/plugins/core/hsize 2
  dconf write /org/compiz/profiles/unity/plugins/unityshell/launcher-minimize-window false
  dconf write /org/gnome/desktop/wm/preferences/action-middle-click-titlebar "'none'"
  dconf write /org/gtk/settings/file-chooser/show-hidden true
  dconf write /org/gnome/nautilus/list-view/use-tree-view true
  dconf write /com/canonical/indicator/power/show-time true
  dconf write /com/canonical/indicator/power/show-percentage true
}

function task_settings {
  # set timezone
  timedatectl set-timezone Europe/Berlin
  # set atom proxy if needed
  if [[ -n $http_proxy ]] && hash apm &>/dev/null; then
    apm config set proxy "$http_proxy"
    apm config set https_proxy "$https_proxy"
  fi
  # install buildnotify desktop
  chmod u+x data/autostart/buildnotify.desktop
  sudo cp data/autostart/buildnotify.desktop /usr/share/applications
}

function task_cursor {
  echo -e "${echo_cyan}Installing custom x-cursor theme 'numix'${echo_normal}"
  git clone https://github.com/uloco/numix-cursor.git
  if [[ ! -d "$HOME/.icons" ]]; then
    mkdir "$HOME/.icons"
  fi
  if [[ ! -d "$HOME/.icons/Numix-Cursor" ]]; then
    cp -rv numix-cursor/theme/Numix-Cursor "$HOME/.icons/Numix-Cursor"
  fi
  gsettings set org.gnome.desktop.interface cursor-theme "Numix-Cursor"
  rm -rf numix-cursor/

}

function task_hardcodefixer {
  echo -e "${echo_cyan}Fixing hardcoded desktop icons${echo_normal}"
  git clone https://github.com/Foggalong/hardcode-fixer.git
  cd hardcode-fixer
  sudo ./fix.sh
  cd ..
  rm -rf hardcode-fixer

  # fix webstorm
  sudo sed -i "/^Icon/c\Icon=webstorm" /usr/share/applications/jetbrains-webstorm.desktop
}

function task_themeing {
  # numix
  sudo add-apt-repository -y ppa:numix/ppa
  sudo apt-get update

  sudo apt-get install -y numix-gtk-theme \
    numix-icon-theme-circle

  gsettings set org.gnome.desktop.wm.preferences theme 'Numix'
  gsettings set org.gnome.desktop.interface gtk-theme 'Numix'
  gsettings set org.gnome.desktop.interface icon-theme 'Numix-Circle'

  task_hardcodefixer
  task_cursor
}

# install android sdk
function task_android {

  # perhaps this is enough
  echo -e "${echo_cyan}Installing android${echo_normal}"

  $CURRENT_DIR=$(pwd);

  # download android sdk
  wget https://dl.google.com/android/android-sdk_r24.4.1-linux.tgz
  tar -xvf android-sdk_r24.4.1-linux.tgz
  mv android-sdk-linux "$HOME/Software/"

  # install missing libs
  sudo apt-get -y install libbz2-1.0
  sudo apt-get -y install lib32z1 lib32ncurses5 lib32stdc++6

  # set path
  echo -e '\n# Set android path\nexport PATH=${PATH}:${HOME}/Software/android-sdk-linux/tools:${HOME}/Software/android-sdk-linux/platform-tools\nexport ANDROID_HOME=${HOME}/Software/android-sdk-linux' >> "$HOME/.bashrc"
  source "$HOME/.bashrc"

  # run sdk manager
  android &

  rm android-sdk_r24.4.1-linux.tgz
  cd "$CURRENT_DIR";
}

function task_terminal {
  echo -e "${echo_cyan}Setting up terminal colors and prompt${echo_normal}"

  git clone --depth=1 https://github.com/Bash-it/bash-it.git "$HOME/.bash_it"
  echo 'y' | "$HOME/.bash_it/install.sh"

  source "$HOME/.bashrc"

  bash-it enable alias git
  cp -r data/powerline-nice "$HOME/.bash_it/themes/"

  sed -i "/^export BASH_IT_THEME/c\export BASH_IT_THEME=\'powerline-nice\'" "$HOME/.bashrc"
}

function task_alternatives {
  sudo sed -i 's/gedit.desktop/atom.desktop/g' /etc/gnome/defaults.list
}
