#!/usr/bin/env bash

default_branch() {
  git symbolic-ref refs/remotes/origin/HEAD | sed 's@^refs/remotes/origin/@@'
}

git checkout "$(default_branch)" &>/dev/null && git branch -vv | grep "origin/.*: gone]" |
  awk "{print \$1}" | xargs git branch -d
