#!/usr/bin/env bash

CONF='/etc/cntlm.conf'

shopt -s extglob

USER_NAME="$(sudo cat "$CONF" | grep Username)";
USER_NAME="${USER_NAME##Username+([[:space:]])}";

DOMAIN="$(sudo cat "$CONF" | grep Domain)";
DOMAIN="${DOMAIN##Domain+([[:space:]])}";

echo "User: $USER_NAME"
echo "Domain: $DOMAIN"

echo -n "Password: ";
PW="$(cntlm -u $USER_NAME -d $DOMAIN -f -H)";


echo "Adding to /etc/cntlm.conf";
PASSLM="$(echo "$PW" | grep PassLM)";
PASSNT="$(echo "$PW" | grep -e 'PassNT ')";
PASSNTLM="$(echo "$PW" | grep PassNTLMv2)";

sudo sed -i '/PassLM /c\'"$PASSLM" "$CONF"
sudo sed -i '/PassNT /c\'"$PASSNT" "$CONF"
sudo sed -i '/PassNTLMv2 /c\'"$PASSNTLM" "$CONF"

echo "Restarting service"
sudo service cntlm restart

shopt -u extglob
